### ISSUE TITLE
python merge_jsons.py : num-folder-per-job missing argument 

### ISSUE THREAD

**Issue by EvgeniaChroni** [facebookresearch/CutLER#11]
Hello, 

Thank you for your work. 

For MaskCut part the following command is provided by your instructions.  

python merge_jsons.py \
--base-dir /path/to/save/annotations \
--num-folder-per-job 2 --fixed-size 480 \
--tau 0.15 --N 3 \
--save-path imagenet_train_fixsize480_tau0.15_N3.json

However, num-folder-per-job argument does not exist in merge_jsons.py file.

**Comment by frank-xwang** [comment]
Hi @EvgeniaChroni, thank you for your comments! Yes, it is a typo. merge_jsons.py has been updated. Please let me know if it works now.
