### ISSUE TITLE
maskcut_with_submitit.py has no attribute 'get_args_parser' 

### ISSUE THREAD

**Issue by blue-butterfly** [facebookresearch/CutLER#12]
Hi, thanks for your great work !  
But  when I  run_maskcut_with_submitit.sh,  I have a problem that main_func( maskcut_with_submitit )  has no attribute 'get_args_parser' ?

**Comment by frank-xwang** [comment]
Hi @blue-butterfly, thanks for your comments. We have made some changes to both run_maskcut_with_submitit.sh and maskcut_with_submitit.py. Please let us know if the bug has been fixed.

**Comment by blue-butterfly** [comment]
Thanks very much! It works now ~
