### ISSUE TITLE
Self-training error

### ISSUE THREAD

**Issue by Greybeast** [facebookresearch/CutLER#13]
After having generated the json for the first round of training, I get this error. The given snippet asks to provide the train-dataset value for round1 training, but it seems script does not take train-dataset input. Is it the "test-dataset" that should be provided? 

python train_net.py --num-gpus 8 \
  --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN_self_train.yaml \
  --**train-dataset** imagenet_train_r1 \
  MODEL.WEIGHTS output/model_final.pth \ # load previous stage/round checkpoints
  OUTPUT_DIR output/self-train-r1/ # path to save checkpoints

**Error:**
usage: train_net.py [-h] [--config-file FILE] [--resume] [--eval-only] [--num-gpus NUM_GPUS] [--num-machines NUM_MACHINES] [--machine-rank MACHINE_RANK] [--test-dataset TEST_DATASET]
                    [--no-segm] [--dist-url DIST_URL]
                    ...
train_net.py: error: unrecognized arguments: --train-dataset

I have used a very very small subset of imagenet and have successfully executed till generation of cutler_imagenet1k_train_r1.json. Please help!

**Comment by frank-xwang** [comment]
Hi @Greybeast, we have updated the codes to fix this issue.

Also, you can remove the "--train-dataset imagenet_train_r1" command and modify the arguments in "model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN_self_train.yaml" directly. This is Detectron2's recommended way to change configurations. 

Both methods should fix your bugs. Please let us know if they work. Thank you! 
XD

**Comment by frank-xwang** [comment]
Closing it now. Please feel free to reopen it if have further questions.
