### ISSUE TITLE
Score for AP calculation

### ISSUE THREAD

**Issue by lxa9867** [facebookresearch/CutLER#18]
Hi,

Thank you for sharing such a work. I would like to ask what is used as score to compute AP_mask when just using MaskCut as reported in Table~7.

**Comment by frank-xwang** [comment]
Hi! Since MaskCut does not provide a score, we will need to use all the masks available to evaluate the AP_mask.

**Comment by lxa9867** [comment]
Is it equivalent to set all the scores to 1?

**Comment by frank-xwang** [comment]
Certainly! As long as you do not set a threshold when evaluating AP_mask using COCO's official evaluation metric, the value used for the confidence score (whether it is 0.1, 1.0, or 0.000001) should not have any influence on the AP. You can check [this blog](https://blog.zenggyu.com/en/post/2018-12-16/an-introduction-to-evaluation-metrics-for-object-detection/), which gives a pretty good explanation of the evaluation metric.

**Comment by lxa9867** [comment]
I see, thank you!

**Comment by lxa9867** [comment]
Hi,

Thank you for your patient answers. Can you please let me know, without a score or a series of threshold, how to calculate the P-R curve? I am quite confused and still believe you cannot calculate AP if you don't have a score. Thank you

**Comment by frank-xwang** [comment]
As mentioned earlier, although the pseudo-masks produced by MaskCut do not have a confidence score (and we cannot get a confidence score), we can still assign a confidence score of 1.0 to all masks. The AP (average precision) is calculated using interpolated precision-recall, as explained in the cocoapi documentation. By assigning the same confidence score to all masks, we get an interpolated P-R curve that is a horizontal line. To understand the calculation method in more detail, you can refer to the [cocoapi](https://github.com/cocodataset/cocoapi), which is the same tool we used to obtain the AP_mask metric in table 7.

**Comment by lxa9867** [comment]
Thank you so much for the detailed explanation! I understand it.

**Comment by bio-mlhui** [comment]
Hello, wonderful work! I want to know how to reproduce the MaskCut results in table 7. I use the code of maskcut.py and evaulation codes same to Cutler on cls_ag_coco. But the AP_mask is near to zero. Could you provide more details? Thanks so much!

**Comment by bio-mlhui** [comment]
I think it maybe because MaskCut only can predict 3 objects, while Cutler can predict 100 objects. This makes recall value small for MaskCut.

**Comment by bio-mlhui** [comment]
Sorry for my mistake. I forget to resize the mask into the original image size. Everything works fine.
