### ISSUE TITLE
gpu memory is increasing as training  

### ISSUE THREAD

**Issue by blue-butterfly** [facebookresearch/CutLER#20]
Hi, thanks for your great work !
But when I train as the README, the gpu  memory is increasing， Then out of memory ？ The commands as follow：

cd cutler
export DETECTRON2_DATASETS=/path/to/DETECTRON2_DATASETS/
python train_net.py --num-gpus 2 \
  --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN.yaml

**Comment by frank-xwang** [comment]
Hi! I recommend using 8 GPUs to run the experiments. However, suppose you are limited to 2 GPUs. In that case, you may need to adjust the batch size, learning rate, and the number of iterations accordingly to avoid encountering an out-of-memory error.

I am closing this issue now. Please feel free to reopen it if you have more questions.

**Comment by khatanas** [comment]
Perfect! 
Thank you 👍
