### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by lukkaal** [facebookresearch/CutLER#26]
what dose “ The datasets are assumed to exist in a directory specified by the environment variable DETECTRON2_DATASETS. Under this directory, detectron2 will look for datasets in the structure described below, if needed.” mean?

**Comment by lukkaal** [comment]
Btw thx for ur amazing work!

**Comment by frank-xwang** [comment]
You need to use "export DETECTRON2_DATASETS=/path/to/dataset/" to ensure that detectron2 can find your datasets. For more details, please check [detectron2's readme. ](https://github.com/facebookresearch/detectron2/blob/main/datasets/README.md)

**Comment by frank-xwang** [comment]
I am closing it now. Please feel free to reopen it if you have further questions.
