### ISSUE TITLE
Generating Annotations for VOC with MaskCut

### ISSUE THREAD

**Issue by zqwang21** [facebookresearch/CutLER#28]
Hey, thanks for your work!
I have tried to generate anotations for voc with maskcut, but there are garbled characters in the generated json file when it comes to annotation_info. 
(The command i ran is python maskcut.py  --vit-arch base --patch-size 8  --tau 0.15 --fixed_size 480 --N 3  --num-folder-per-job 1000 --job-index 0  --dataset-path /path/to/dataset/traindir --out-dir /path/to/save/annotations )
![image](https://user-images.githubusercontent.com/78678070/233304844-6114df98-e779-4f90-b56e-b1ab88de199d.png)
And I have changed decoding method from ascii to gbk and utf-8, but it still does not work.
![image](https://user-images.githubusercontent.com/78678070/233305526-7e11778f-b7b1-41f1-8580-e9c74674b345.png)

Do you have any idea about this?

**Comment by zqwang21** [comment]
After debugging the maskcut.py, it is found that the value of counts  are garbled. Why  does it happen? How to solve it ?
![image](https://user-images.githubusercontent.com/78678070/233326308-7def513c-2242-4702-9c5f-11d69d9751c4.png)

**Comment by zqwang21** [comment]
![image](https://user-images.githubusercontent.com/78678070/233338262-0a23457a-4ea5-47cf-830f-6d3337688201.png)

**Comment by frank-xwang** [comment]
By the way, it is recommended to stick with the RLE format for mask annotation unless you have a specific reason to use the polygon format, as the former is more efficient in terms of storage and computation.

**Comment by frank-xwang** [comment]
Closing it now. Please feel free to reopen it if you have further questions!

**Comment by zqwang21** [comment]
Hey, i have some new problems!


i have deleted segmentation,height,width code in annotation_info which are grabled&nbsp; in order to&nbsp; generate annotations for voc, because the jsonfile of voc&nbsp; download from github&nbsp; also&nbsp; does not include this part of code. However , after generating the jsonfile and running the&nbsp; command
（ python train_net.py --num-gpus 3 \
&nbsp; --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN.yaml \
&nbsp; --test-dataset cls_agnostic_voc --no-segm \
&nbsp; --eval-only MODEL.WEIGHTS "/home/yli/CutLER-main/cutler_cascade_final.pth"）, AP is 64.58 which is much higher than the value in modelzoo&nbsp; which you offered. Therefore, i compared those two jsonfiles,&nbsp; bbox information in my jsonfile&nbsp; is much less than yours. i do not why, do you have any idea?



By the way , my steps are followings: 1) downlowad VOC2007 JPEGImages 2)run the command :python maskcut.py --vit-arch base --patch-size 8&nbsp; 3)specify the jsonfile in cutler/data/datasets/builtin.py 4)&nbsp; run the command:python train_net.py --num-gpus 3&nbsp;
&nbsp; --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN.yaml \
&nbsp; --test-dataset cls_agnostic_voc --no-segm \
&nbsp; --eval-only MODEL.WEIGHTS "/home/yli/CutLER-main/cutler_cascade_final.pth")
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/CutLER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 凌晨2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/CutLER] Generating Annotations for VOC with MaskCut (Issue #28)





 
Closing it now. Please feel free to reopen it if you have further questions!

**Comment by zqwang21** [comment]
&nbsp;The yellow boxes are&nbsp; my jsonfile visualized&nbsp; results, the red boxes are yours. why are our jsonfiles inconsistent?&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/CutLER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 凌晨2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/CutLER] Generating Annotations for VOC with MaskCut (Issue #28)





 
Closing it now. Please feel free to reopen it if you have further questions!

**Comment by frank-xwang** [comment]
Hi, could you please resend your questions? There are many &nbsp symbols, it is hard to read your message. Thanks!

**Comment by zqwang21** [comment]
Sorry，i rephrase my questions.
i have deleted segmentation, height, and width code in annotation_info which are grabled,  in order to generate annotations for voc, because the jsonfile of voc download from github also does not include this part of code.
![image](https://user-images.githubusercontent.com/78678070/233849286-365b1468-494d-4362-86d3-6b3cf592f41d.png)

 However , after generating the jsonfile and running the command
（ python train_net.py --num-gpus 3 \
 --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN.yaml \
 --test-dataset cls_agnostic_voc --no-segm \
 --eval-only MODEL.WEIGHTS "/home/yli/CutLER-main/cutler_cascade_final.pth"）, AP50 is 64.58 which is much higher than the value in modelzoo which you offered. Therefore, i compared those two jsonfiles, I found that bbox information in my jsonfile is different from yours. i do not know why there are these differences, do you have any idea?
![image](https://user-images.githubusercontent.com/78678070/233848972-e913fd5d-58d1-41c0-9a4c-26447aaa99b5.png)

The yellow boxes are my jsonfile visualized results, the red boxes are yours. why are our jsonfiles inconsistent?
![image](https://user-images.githubusercontent.com/78678070/233849063-25d462af-ee86-4d8e-b519-ecfa0193367d.png)

By the way , my steps are followings: 

1. downlowad VOC2007 JPEGImages 
2. run the command :python maskcut.py --vit-arch base --patch-size 8 
3. specify the jsonfile in cutler/data/datasets/builtin.py 
4. run the command: 

    python train_net.py --num-gpus 3
 --config-file model_zoo/configs/CutLER-ImageNet/cascade_mask_rcnn_R_50_FPN.yaml \
 --test-dataset cls_agnostic_voc --no-segm \
 --eval-only MODEL.WEIGHTS "/home/yli/CutLER-main/cutler_cascade_final.pth")

**Comment by zqwang21** [comment]
i also  evaluated the model's performance on VOC using the jsonfile download from your github, the result is the same as what you submitted in  modelzoo. i feel that my steps are correct, but why my jsonfile generated by maskcut is different from yours？

**Comment by zqwang21** [comment]
[voc_annotations.zip](https://github.com/facebookresearch/CutLER/files/11311144/voc_annotations.zip)
This is my jsonfile annotations generated according to the steps described above, do you have any idea why it is different  from yours? And how can my result be consistent with yours?

**Comment by frank-xwang** [comment]
Answered in #29.
