### ISSUE TITLE
VOC annotations generated by maskcut 

### ISSUE THREAD

**Issue by zqwang21** [facebookresearch/CutLER#29]
Hey, this is my jsonfile for VOC  annoatations generated by maskcut ,but the bbox information is different from the file you submitted in github. Therefore I visualize the results of both of us on JPEGImages/009829.jpg  ，the yellow boxes are mine and the red are yours. 
![image](https://user-images.githubusercontent.com/78678070/234022918-3662ac9a-188b-48be-b818-9107fbbba688.png)
Do you have any idea why there are these differences? 
[voc_annotations.zip](https://github.com/facebookresearch/CutLER/files/11311341/voc_annotations.zip)

https://github.com/facebookresearch/CutLER/issues/28#issuecomment-1519094466

**Comment by frank-xwang** [comment]
Hi, the JSON file we provided contains ground truth annotations that have been converted to COCO-style format. The main purpose of providing this file is to evaluate the zero-shot unsupervised detection performance of our model. Also, the coco-style bounding box format should be [x_min, y_min, width, height], which is different from the voc format.
