### ISSUE TITLE
About cutler/demo/demo.py

### ISSUE THREAD

**Issue by minjin123** [facebookresearch/CutLER#32]
Thank you for posting your code.

When I run `cutler/demo/demo.py`, I get same results as shown in images below
I download the detectron2 with Linux (torch 1.12/ cuda 11.3) and use A6000 GPUs.

I followed [this](https://github.com/facebookresearch/CutLER#inference-demo-for-cutler-with-pre-trained-models).
**But, I have two issues.**
**(1)** the results are strange.
**(2)** whenever I run `this file`, the results change.

**Result1**
![demo1](https://github.com/facebookresearch/CutLER/assets/100121244/b4fd98f5-6ccb-4cd6-8754-df8cfb27274c)

**Result2**
![demo1](https://github.com/facebookresearch/CutLER/assets/100121244/ca7c93d9-1015-470c-a890-357fa56cb5b4)

Could I have missed something?

I look forward to hearing from you.

**Comment by yjdzyr** [comment]
Have you solved your problem

**Comment by xy1565838851** [comment]
load the checkpoint, otherwise random init
