### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.TokenCut.unsupervised_saliency_detection'

### ISSUE THREAD

**Issue by W-hary** [facebookresearch/CutLER#33]
File "maskcut.py", line 25, in <module>

from third_party.TokenCut.unsupervised_saliency_detection import utils, metric

Sorry, I can't find what the third_party module is, could you please point it? Very thanks!

**Comment by frank-xwang** [comment]
Hello! To clone this repository, please use the following command:
git clone --recursive git@github.com:facebookresearch/CutLER.git
This command will automatically download all the necessary third-party codes alongside the main repository.

**Comment by frank-xwang** [comment]
Closing it
