### ISSUE TITLE
Can I achieve more fine-grained segmentation? 

### ISSUE THREAD

**Issue by loopyli** [facebookresearch/CutLER#35]
Can I achieve more fine-grained segmentation? For example, dividing the parts of an object.Thanks for your reply.

**Comment by frank-xwang** [comment]
Yes, certainly. To obtain more fine-grained segmentation masks, you can consider applying the normalized cut algorithm to the initial masks. This algorithm can help to provide more fine-grained results.

Alternatively, you can also explore using k-Means clustering or spectral clustering methods to obtain more part segmentation masks. These clustering techniques can help further partition the objects into smaller regions or parts, allowing for a more comprehensive and detailed segmentation of the objects in the image.

**Comment by frank-xwang** [comment]
Closing it now. Please feel free to reopen it if you have further questions.
