### ISSUE TITLE
Official Evaluation on COCO val2017 with MaskCut only

### ISSUE THREAD

**Issue by LeslieTrue** [facebookresearch/CutLER#41]
Hi Xudong and all, 
I'm new to segmentation/detection and I'm right now dealing with the evaluation metric of the predicted annotations generated by simply the MaskCut process on COCO validation 2017 set which contains 5k images. I'm wondering if you have any existing approach/code to evaluate the generated JSON file? If so, it would be a great help to me!

Thank you so much!

**Comment by conordete** [comment]
Hi there!
I was also looking for the evaluation code for just MaskCut, not CutLER. Would be great to have this part of the codebase for better evaluation :) Is there any way you can help here? 
Thanks in advance!

**Comment by bio-mlhui** [comment]
Also looking for MaskCut evaluation code/configs.
