### ISSUE TITLE
where are '{1,2,5,10,20,30,40,50,60,80}perc_instances_train2017.json'

### ISSUE THREAD

**Issue by lemonbuilder** [facebookresearch/CutLER#43]
Hello!
I'm going to prepare a coco-dataset for training according to your [guidelines](https://github.com/facebookresearch/CutLER/blob/main/datasets/README.md#expected-dataset-structure-for-coco-coco20k-lvis).
but, there are no '{1,2,5,10,20,30,40,50,60,80}perc_instances_train2017.json'
How can I download a **'1perc_instances_train2017.json'** file ??

**Comment by frank-xwang** [comment]
Hi, we have provided these annotations at this [link](http://dl.fbaipublicfiles.com/cutler/coco-smi/annotations.zip).

**Comment by lemonbuilder** [comment]
> Hi, we have provided these annotations at this [link](http://dl.fbaipublicfiles.com/cutler/coco-smi/annotations.zip).

Thanks a lot !
