### ISSUE TITLE
maskcut.py; the meaning of arguments 

### ISSUE THREAD

**Issue by lemonbuilder** [facebookresearch/CutLER#44]
Thanks for sharing your model.
I'm going to train my custom dataset, and make psuedo-masks with MaskCut.
Could I know the meaning of each argument that goes into 'maskcut.py'?

> cd maskcut
> 
> python maskcut.py 
> --vit-arch base   #01.
> --patch-size 8   #02.
> --tau 0.15   #03.
> --fixed_size 480   #04.
> --N 3   #05.
> --num-folder-per-job 1000   #06.
> --job-index 0   #07.
> --dataset-path /path/to/dataset/traindir 
> --out-dir /path/to/save/annotations 

#01. what is '--vit-arch' ? Are there any options other than 'base'?
#02. Is '--patch-size' the correct number of segments for the input-image?
#03. what is '--tau' ?
#04. what is '--fixed_size' ?
#05. '--N' is the number of objects that must be masked in that image, right? Is it a Maximum number??
#06. Is 'num-folder-per-job' the number of folders that make up the input-data?
#07. what is '--job-index' ?

If you could answer this questions, it would be really helpful to use the CutLer :)

**Comment by lemonbuilder** [comment]
@frank-xwang

**Comment by frank-xwang** [comment]
Hi, please refer to [this link](https://github.com/facebookresearch/CutLER/blob/5179f3667211e65de2112b924295bdedfee2d94e/maskcut/maskcut.py#L305) for explanations pertaining to each argument.
