### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.TokenCut.unsupervised_saliency_detection'

### ISSUE THREAD

**Issue by mamarasulovs** [facebookresearch/CutLER#46]
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    from third_party.TokenCut.unsupervised_saliency_detection import metric
ModuleNotFoundError: No module named 'third_party.TokenCut.unsupervised_saliency_detection'

**Comment by frank-xwang** [comment]
Hi, please use `git clone --recursive git@github.com:facebookresearch/CutLER.git` to clone CutLER and all third-party repositories.
