### ISSUE TITLE
Can't download a model from the model zoo.

### ISSUE THREAD

**Issue by FYY799** [facebookresearch/CutLER#47]
Can't download a model from the model zoo.

**Comment by frank-xwang** [comment]
Hello, could you specify which model you were unable to download? We have released many models, so providing more details will help me assist you better.

**Comment by FYY799** [comment]
Any pth.

**Comment by frank-xwang** [comment]
To get the checkpoint address, you can right click on the download link in the model zoo (see attached screenshot).
<img width="866" alt="Screenshot 2023-10-10 at 8 55 48 AM" src="https://github.com/facebookresearch/CutLER/assets/58996472/04805b1f-094b-460c-8dfe-e1f18e91b716">

**Comment by FYY799** [comment]
Thanks.
