### ISSUE TITLE
eigh() got an unexpected keyword argument 'subset_by_index'

### ISSUE THREAD

**Issue by yjdzyr** [facebookresearch/CutLER#48]
Two warning
UserWarning: Default upsampling behavior when mode=bicubic is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)

 UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  "The default behavior for interpolate/upsample with float scale_factor changed "

  One error
TypeError: eigh() got an unexpected keyword argument 'subset_by_index'

**Comment by frank-xwang** [comment]
Hey, could you provide more details on it, such as your torch version? We used pytorch1.8 for almost all experiments, you may want to downgrade your torch to v1.8.

**Comment by yjdzyr** [comment]
尊敬的作者，您好！


我非常高兴能收到您的回答，这是我第一次和大佬交流，我非常激动！我看到文章作者是中国人并且我的英语水平比较一般，所以以中文回复您，还请您见谅。您给出的回答非常正确，我检查了一下我的版本，确实和您项目所需求的版本不同，故导致了这个错误。再次谢谢您的回答。


另外我还有一个问题想和您了解一下，如果您有时间回答我将不胜感激！
我是一名刚刚入学的研究生，阅读到您的论文感觉您的想法非常棒！但是因为我的深度学习的基础较差，是一名跨专业的考生。目前只是看完了简单的pytorch的使用和李沐老师的一些课程以及吴恩达老师的一些课程，可我还是感觉自己在这方面学习起来很困难（就像在您的项目中，我下载了您的代码，但是运行起来出现各种各样的问题，无奈才去您的仓库中留言寻求问题答案，但还好我根据那个报错去寻找原函数，发现确实是没有这个参数，故感觉是因为版本更新增加了一些新的参数，当把对应版本更新完成后，该问题迎刃而解，也确实被您的回答解决，同时我也很惊叹您有这样的能力，透过问题看到其本质！）所以目前我开始阅读顶会论文，提升自己对目标检测方向的理解，每每阅读到一篇新的论文总是被其新颖的创意所折服，但是我自己却没有能力去发现这样的创意。所以我很苦恼，我觉得是我的学习路线有些问题，导致入门困难。我想请教一下您，对于这个方向我应该如何去学习。


祝您身体健康，工作顺利！如果能收到您的回信我将万分感谢！
by：一个刚刚入门的小同学


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "facebookresearch/CutLER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月25日(星期三) 凌晨2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [facebookresearch/CutLER] eigh() got an unexpected keyword argument 'subset_by_index' (Issue #48)





 
Hey, could you provide more details on it, such as your torch version? We used pytorch1.8 for almost all experiments, you may want to downgrade your torch to v1.8.
