### ISSUE TITLE
backbone change

### ISSUE THREAD

**Issue by Alexanderisgod** [facebookresearch/CutLER#49]
when i replace the Vit backbone to resnet, maskcut result uncorrect mask, so the backbone can only use Transformer ways?

**Comment by frank-xwang** [comment]
Given that MaskCut requires the application of normalized cuts to the patch-wise affinity matrix to produce segmentation masks, utilizing a ViT-based backbone becomes imperative. Moreover, the emerging segmentation properties are observed in self-supervised vision transformers, as detailed in the DINO paper. Consequently, MaskCut needs to harness the capabilities of the self-supervised ViT model for effective unsupervised segmentation.
