### ISSUE TITLE
Notebook not working

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [facebookresearch/CutLER#5]
Running the notebook results in missing module `colormap`, installing it resulting in missing module `easydev`, after installing it I got `ImportError: cannot import name 'random_color' from 'colormap' (/usr/local/lib/python3.8/dist-packages/colormap/__init__.py)`

I am wondering how you run it, looking at the torch version it looks like you may have run it some months ago.

Thank you for the help

Cheers,

Fra

**Comment by frank-xwang** [comment]
Hi Fra,

I appreciate your interest in our work. I wanted to follow up on your issue with running the MaskCut demo. I just directly tested the demo on CoLab, and it seems to be working fine. Are you currently running the demo notebook on your local machine? If so, please ensure that the MaskCut demo notebook is located within the CutLER/maskcut/ directory. The colormap is imported from maskcut/colormap.py. You may need to uninstall the colormap package you installed first. 

Please let me know if this resolves the issue you were experiencing.

Best,
Xudong

**Comment by FrancescoSaverioZuppichini** [comment]
Weird, I've tried on collab - maybe a lucky run? Glad the issue was just from my side. I've retried and it runs smoothly, thanks for the great work ❤️ 

Other colleagues have confirmed to me the notebook is running perfectly 🚀

**Comment by YugangDuan** [comment]
> Running the notebook results in missing module `colormap`, installing it resulting in missing module `easydev`, after installing it I got `ImportError: cannot import name 'random_color' from 'colormap' (/usr/local/lib/python3.8/dist-packages/colormap/__init__.py)`
> 
> I am wondering how you run it, looking at the torch version it looks like you may have run it some months ago.
> 
> Thank you for the help
> 
> Cheers,
> 
> Fra

same problem, It can work on colab, but not work on service

**Comment by frank-xwang** [comment]
Hi, please ensure that the MaskCut demo notebook is located within the CutLER/maskcut/ directory. The colormap is imported from maskcut/colormap.py. Based on your error message, it seems like the colormap was imported from "/usr/local/lib/python3.8/dist-packages/colormap/__init__.py", which is wrong. You may need to uninstall the colormap package you installed first or follow our installation instructions to build a new conda environment. 

Best,
XD
