### ISSUE TITLE
Compatibility of Cut and Learn (CutLER) Model with Windows 

### ISSUE THREAD

**Issue by Osasbro** [facebookresearch/CutLER#56]
I am interested in using the Cut and Learn (CutLER) Model for my project, but I am uncertain about its compatibility with the Windows operating system. Can anyone confirm if the CutLER Model can run on Windows, and if so, are there any specific steps or considerations I should be aware of?

If the CutLER Model is not compatible with Windows, I would appreciate any recommendations for alternative models with similar capabilities that are known to work seamlessly on the Windows platform. Thank you.

**Comment by frank-xwang** [comment]
Hi, our model is built-upon detectron2, you can follow this [guideline on detectron2](https://github.com/facebookresearch/detectron2/issues/5114) and [blog](https://helloshreyas.com/how-to-install-detectron2-on-windows-machine) to install detectron2 on windows machine.
