### ISSUE TITLE
Can Cutler be converted to trt engine file

### ISSUE THREAD

**Issue by csoham96** [facebookresearch/CutLER#57]
Hi so i was using cutler and decided to convert into trt engine to enhance the efficiency,

So as you know your pretrained cutler model is based on detectron2 framework and they have a step by step process to convert a model to onnx first and then to trt.

While i was able to create onnx file using first conversion ,
during secondary conversion i am getting issues
  `File "TensorRT/samples/python/detectron2/create_onnx.py", line 482, in roi_heads
    bbox_pred_reshape = self.graph.op_with_const("Reshape", "bbox_pred/reshape", bbox_pred.outputs[0], bbox_pred_shape)
AttributeError: 'NoneType' object has no attribute 'outputs'` 
Do you guys have any support regarding this on how to convert model into appropriate trt convertable onnx file for Custom roi heads/Culter?

**Comment by frank-xwang** [comment]
Hi, our model is based on Detectron2, you can check this posted [issues](https://github.com/facebookresearch/detectron2/issues/4202) under Detectron2 to address your issue. Thanks!
