### ISSUE TITLE
Zero-shot detection evaluation

### ISSUE THREAD

**Issue by chaos1992** [facebookresearch/CutLER#8]
Thanks for your great work. I have a confusion about the zero-shot evaluation. In the 'cascade_mask_rcnn_R_50_FPN.yaml' config file,  ROI_HEADS.NUM_CLASSES is setted to 1, so CutLER only can distinguish the foreground objects and background objects. However, such as in COCO dataset, there are 80 different classes, how CutLER compute the AP50 metric in zero-shot?

**Comment by hetavv** [comment]
Could anyone confirm if my understand of Zero-shot detection is correct or not? My understanding is all the objects are assigned a singular label, say "object" and then treat the detected bounding boxes with label "object" and keep it similar in the ground truth as well? Thanks
