### ISSUE TITLE
training slow

### ISSUE THREAD

**Issue by jxgu1016** [facebookresearch/CutLER#9]
Hi, thanks for this good work.

I run the training on 8 A100 gpus and find it will cost almost 20 days to finish one round training. Is that normal? How much time it will cost you to train one round?

**Comment by jxgu1016** [comment]
More details, the GPU Uitil. is very low

**Comment by frank-xwang** [comment]
Closing it now. Please feel free to reopen it if you have any more questions.

**Comment by linyq2117** [comment]
Hi, 

I also came across this problem during training. I changed the num_workers but the training time is still too long (more than 10 days). The GPU Uitill had no improvement by increasing num_workers. Did you solve it? @jxgu1016 @frank-xwang

**Comment by linyq2117** [comment]
I find the reason. This problem is caused by the COPY_PASTE operation. It is operated on CPU and thus heavily slows down the training speed.
